### ISSUE TITLE
Timeouts are too short

### ISSUE THREAD

**Issue by rabernat** [pangeo-gallery/binderbot#8]
In https://github.com/rsignell-usgs/esip-gallery/issues/4 we are discussing binderbot timing out when executing a notebook. There are many layers of timeouts in the code. The one that triggered the failure is this, from nbconvert

https://github.com/pangeo-gallery/binderbot/blob/0b0ef65f445118ab97510d423bcf2e115c8d087e/binderbot/binderbot.py#L265-L270

We should either:
- increase the default timeouts
- make the timeouts customizable via the CLI

Would love some thoughts.

**Comment by rsignell-usgs** [comment]
Is one idea to allow specification in the `binderbot.yaml`, like [this one](https://github.com/rsignell-usgs/esip-gallery/blob/master/.github/workflows/binderbot.yaml)?

**Comment by andersy005** [comment]
I am running into a [similar issue](https://github.com/andersy005/cesm-lens-aws/runs/579786928?check_suite_focus=true) as well. 


> make the timeouts customizable via the CLI

:+1:

**Comment by rabernat** [comment]
The latest version of the CLI includes the `--nb-timeout` option. The default (600; 10 minutes), can be customized in your workflow script.
